[workspace]
authors = ["reonokiy <reonokiy@nokiy.net>"]
channels = ["conda-forge"]
name = "ELF"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10"
setuptools = "==69.5.1"
numpy = ">=1.26.4,<2.0.0"
scipy = ">=1.12.0"
matplotlib = ">=3.8.0"
requests = ">=2.31.0"
tqdm = ">=4.66.0"
pillow = ">=9.5.0"
pyyaml = ">=6.0.1"

[pypi-dependencies]
torch = {url = "https://download.pytorch.org/whl/cu129/torch-2.11.0%2Bcu129-cp312-cp312-manylinux_2_28_x86_64.whl"}
torchvision = {url = "https://download.pytorch.org/whl/cu129/torchvision-0.26.0%2Bcu129-cp312-cp312-manylinux_2_28_x86_64.whl"}
einops = ">=0.7.0"
huggingface-hub = ">=0.23.0"
transformers = ">=4.41.2"
